//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define Brianne_s_hand                  4
#define OPENAL32                        6
#define WORLD_IMAGE                     101
#define FLAG_TAIWAN_IMAGE               102
#define PVZ_BACKGROUND_BG1_IMAGE        103
#define PVZ_SEEDSELECTOR_SEEDCHOOSERBACKGROUND_IMAGE 104
#define PVZ_SEEDSELECTOR_SEEDBANK_IMAGE 105
#define PVZ_SEEDPACKET_PEASHOOTER_IMAGE 106
#define PVZ_SEEDSELECTOR_SEEDCHOOSERDISABLED_IMAGE 107
#define PVZ_SEEDSELECTOR_SEEDCHOOSER_IMAGE 108
#define PVZ_SEEDSELECTOR_STARTREADY_IMAGE 109
#define PVZ_SEEDSELECTOR_STARTSET_IMAGE 110
#define PVZ_SEEDSELECTOR_STARTGO_IMAGE 111
#define GRASSWALK_AUDIO 112
#define CHOOSEYOURSEEDS_AUDIO 113
#define READYSETPLANT_AUDIO 114
#define BATTLEOFWUHAN_AUDIO 115
#define PEASHOOTERIDLEJSON 116
#define PEASHOOTERIDLEPNG 117

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
